### ISSUE TITLE
Suporte para acesso de séries históricas

### ISSUE THREAD

**Issue by miguelfs** [asfixia/ImoveisBH3#1]
Oi, Danilo. Tudo bem?

Primeiramente, queria dizer que gostei bastante do seu projeto, principalmente por criar uma interface de uso público. Se eu fosse mineiro, com certeza usaria a ferramenta!

Estou pesquisando séries históricas de preços, devido a pesquisa do meu TCC. A ideia é criar um modelo preditivo que consuma indicadores econômicos do Banco Central (BACEN) + preços de algum bem do mercado interno. Por fim, avaliar se o conjunto de indicadores do BACEN reduz o erro médio na predição do preço.

Por acaso você teria ou indica uma série histórica de preços e dados de imóvel ou aluguel? Meu contato é mfsousa @ poli.ufrj.br. Não consegui achar seu contato pela sua conta do GitHub :(

Abraço! E parabéns pela aplicação!

**Comment by asfixia** [comment]
Olá Miguel tudo bem obrigado! E com voce?

Infelizmente não tenho uma série historica mas assim tem alguns meses que estou atualizando esse repositório todos os dias.
O Problema é que tem apenas os imóveis de um determinado perfil.
No entanto tem tbm um outro projeto a alguns anos atraz onde eu buscava comparar o preço do imóvel no Mercado X Leilao.
Talvez ao juntar essas duas informações voce consiga uma boa quantidade de dados.

Se os dados aqui presentes forem uteis te aconselho pegar o histórico de commits. (faço um por dia com os imóveis disponíveis naquele dia)

Obrigado! Fico feliz que tenha gostado! :)

Sobre a questão do histórico de preços, se incluir eletrodomesticos talvez seja uma boa usar sites como bondfaro e buscape. Lá tem a variação de preço de muitos produtos no periodo de 6 meses.

**Comment by miguelfs** [comment]
Tudo bem! Vou dar uma olhada nos commits e no caso que você comentou.

Obrigado pela sugestão do Buscapé! Vou dar uma esmiucada na API deles sim! 

No momento, o plano B que meu orientador sugeriu seria prever os preços de ações da Bovespa associadas ao mercado imobiliário nacional, uma vez que há facilidade para obter os dados. Ter um plano C é sempre bom 😆 Abraço!
